config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "dreams#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :dreams do
    collection do
      get 'search', to: 'dreams#search'
    end
  end

  # add dashboard

  get "dashboard", to: "pages#dashboard"

  resources :dreams, except: [:index] do
    resources :bookings, only: %i[new create edit update show] do
      member do
        get 'accept_booking', as: :accept_booking
        get 'refuse_booking', as: :refuse_booking
      end
    end
  end

  resources :bookings, only: %i[index destroy]

  # Defines the root path route ("/")
  # root "posts#index"

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :dream
  attribute :status
  enum :status, { pending: 0, accepted: 1, refused: 2 }

  validates :user_id, presence: true
  validates :dream_id, presence: true

  validates :start_date, uniqueness: { scope: :dream_id, message: "This date is already booked" }
  validates :end_date, uniqueness: { scope: :dream_id, message: "This date is already booked" }
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if start_date.blank? || end_date.blank?

    errors.add(:end_date, "must be after start date") if end_date <= start_date
  end

end

app/models/dream.rb
class Dream < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  has_many_attached :photos

  searchkick

  validates :price, presence: true
  validates :availability, presence: true
  validates :description, presence: true
  validates :title, presence: true
  validates :category, presence: true

  CATEGORIES = %w[Nightmare Daydream Lucid Falling Recurring Initiative Prophetic Astral Travel Black Awakening Tjukurrpa]
  ICONS = ["fa-regular fa-star", "fa-solid fa-eye", "fa-regular fa-droplet", "fa-solid fa-cloud-moon", "fa-solid fa-moon", "fa-solid fa-anchor", "fa-solid fa-volcano"]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :dreams
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find, only: %i[show destroy edit update accept_booking refuse_booking]
  before_action :find_dream, only: %i[new create edit update show]

  def index
    user = current_user.id
    @bookings = Booking.where(:user_id => user)
  end

  def show; end

  def new
    @booking = Booking.new
  end

  def create
    # "We extracted start and end date from the range"
    options= {}
    dates = booking_params[:start_date].split(" to ")
    date_start= dates[0]
    date_end= dates[1]
    params= {start_date: date_start, end_date: date_end}
    @booking = Booking.new(params)
    @booking.user = current_user
    @booking.dream = @dream
    if @booking.save
      redirect_to dream_booking_path(@dream, @booking)
    else
      flash[:error] = @booking.errors.full_messages.to_sentence
      redirect_to new_dream_booking_path(@booking.dream)
    end
  end

  def edit
  end

  def update
    dates = booking_params[:start_date].split(" to ")
    date_start= dates[0]
    date_end= dates[1]
    params= {start_date: date_start, end_date: date_end}
    if @booking.update(params)
      redirect_to dashboard_path
    else
      flash[:error] = @booking.errors.full_messages.to_sentence
      redirect_to edit_dream_booking_path(@booking.dream, @booking)
    end
  end


  def destroy
    @booking.destroy
    redirect_to root_path, status: :see_other
  end

  def accept_booking
    @booking.update(status: 1)
    redirect_to dashboard_path
  end

  def refuse_booking
    @booking.update(status: 2)
    redirect_to dashboard_path
  end

  private

  def find
    @booking = Booking.find(params[:id])
  end

  def find_dream
    @dream = Dream.find(params[:dream_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price, :user_id, :dream_id)
  end
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :search]
  before_action :find_dream, only: [:show, :edit, :update, :destroy]

  def index
    params[:query].present? ? @dreams = Dream.where("category ILIKE ?", "%#{params[:query]}%") : @dreams = Dream.all
  end

  def show
  end

  def new
    @dream = Dream.new
  end

  def create
    @dream = Dream.new(dream_params)
    @dream.user = current_user
    if @dream.save
      redirect_to dream_path(@dream)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @dream.update(dream_params)
  end

  def destroy
    @dream.destroy
    redirect_to root_path status: :see_other
  end

  def search
    @results = Dream.search(params[:q])
    render :index
  end

  private
  def dream_params
    params.require(:dream).permit(:title, :price, :availability, :photos, :description, :category, photos: [])
  end

  def find_dream
    @dream = Dream.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @dreams = Dream.where(user_id: current_user)
    @bookings = Booking.where(user_id: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <div class="row row-cols-3">
    <div class="col m-5">
      <h1>Edit your booking</h1>
      <h1>Fill this new booking for dream <%= @dream.title %></h1>

        <% if flash[:error].present? %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:error] %>
        </div>
        <% end %>

        <%= simple_form_for [@dream, @booking] do |f| %>
        <%= f.input :start_date,
                as: :string,
                label: "Choose a date",
                input_html: { data: { controller: "datepicker" } } %>
        <%= f.button :submit %>
        <% end %>
      </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container mt-5">
  <h1 class="text-center">All your bookings</h1>

  <% @bookings.each do |booking| %>
    <div class="row justify-content-center">
      <div class="col-md-8">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Dream</th>
              <th scope="col">Start Date</th>
              <th scope="col">End Date</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= booking.dream.title %></td>
              <td><%= booking.start_date.strftime("%A, %b %d") %></td>
              <td><%= booking.end_date.strftime("%A, %b %d") %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row row-cols-3">
    <div class="col m-5">
      <h1>Create a new booking</h1>
      <h2>Fill this new booking for dream <%= @dream.title %></h2>

        <% if flash[:error].present? %>
          <div class="alert alert-danger" role="alert">
            <%= flash[:error] %>
          </div>
        <% end %>

        <%= simple_form_for [@dream, @booking] do |f| %>
          <%= f.input :start_date,
                  as: :string,
                  label: "Choose a date",
                  input_html: { data: { controller: "datepicker" } } %>
          <%= f.button :submit %>
        <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<body class="bg-light">

<div class="container mt-5 text-center">
  <h2 class="text-success">Thanks for this booking!</h2>

  <% start_date_formatted = @booking.start_date.strftime("%A, %b %d") %>
  <% end_date_formatted = @booking.end_date.strftime("%A, %b %d") %>

  <h2 class="mt-4">You have booked your dream from <%= start_date_formatted %> to <%= end_date_formatted %></h2>
  <h3 class="mt-4"> The total price of your booking is <%= number_with_delimiter( (@booking.end_date.to_datetime - @booking.start_date.to_datetime).to_i * @booking.dream.price.to_i, delimiter: ' ') %>€</h3>

  <div class="mt-4">
    <%= link_to "Edit your booking", edit_dream_booking_path(@dream, @booking), class: "btn btn-primary mr-2" %>
    <%= link_to "Delete", booking_path(@booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
  </div>
</div>

app/views/dreams/_category_bar.html.erb
<div class="container">
  <div class="inner-flex">
    <%# <div class="row"> %>
      <%Dream::CATEGORIES.each do |category| %>
      <%= link_to dreams_path(query: category), class: "flex__item #{'active' if params[:query] == category}" do%>
        <%# <div class="flex__item"> %>
          <div>

            <i class="<%=Dream::ICONS.sample%>"></i>
          </div>
          <div>
            <p><%=category%></p>
          </div>
        <%# </div> %>
      <%end%>
      <%end%>
    </div>
  <%# </div> %>
</div>

<%# <%=Dream::ICONS.sample(1)%>

app/views/dreams/_form.html.erb
<div class="container">
  <div class="row row-cols-3">
    <div class="col m-5">
      <%= simple_form_for @dream do |f| %>
          <%= f.input :title %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.input :availability %>
        <%= f.input :price %>
        <%= f.input :description %>
        <%= f.input :category, collection: Dream::CATEGORIES %>
        <%= f.button :submit, class: "btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>

app/views/dreams/edit.html.erb
<div class="container m-5">
<h1 class="ms-5 mx-5">Edit your dream</h1>
<%= render "form", dream: @dream %>
<%= link_to "Go back to homepage", root_path, class:"m-5" %>
</div>

app/views/dreams/index.html.erb
<%=render "category_bar"%>

<% if @results %>
    <% @results.each do |dream| %>
      <%= link_to dream_path(dream) do %>
      <div style="height: 150px" class="w-100 my-3 position-relative shadow-sm">
          <h3 class="z-index-2 position-absolute absolution dream_text_effect text-decoration-none text-white ms-2"> <%= dream.title %></h2>
          <div class="position-absolute sliding-background" style="background-image: url('<%= cl_image_path dream.photos[0].key %>')"></div>
      </div>
        <br>
      <% end %>
    <% end %>
  <% else %>
    <% @dreams.each do |dream| %>
      <%= link_to dream_path(dream) do %>
      <div style="height: 150px" class="w-100 my-3 position-relative shadow-sm">
          <h3 class="z-index-2 position-absolute absolution dream_text_effect text-decoration-none text-white ms-2"> <%= dream.title %></h2>
          <div class="position-absolute sliding-background" style="background-image: url('<%= cl_image_path dream.photos[0].key %>')"></div>
      </div>
        <br>
      <% end %>
    <% end %>
<% end %>

app/views/dreams/new.html.erb
<div class="container m-5">
<h1 class="ms-5 mx-5">Add a dream</h1>
<%= render "form", dream: @rdream %>
<%= link_to "Go back to homepage", root_path, class:"m-5" %>
</div>

app/views/dreams/show.html.erb
<div class="container">
  <h1><strong><%= @dream.title %></strong></h1>

<div class="parent">
  <div class="image-div div1" id="left-image" style="background-image: url(<%=cl_image_path(@dream.photos[0].key)%>)"></div>
  <div class="image-div div2" style="background-image: url(<%=cl_image_path(@dream.photos[1].key)%>)"></div>
  <div class="image-div div3" style="background-image: url(<%=cl_image_path(@dream.photos[2].key)%>)"></div>
  <div class="image-div div4" style="background-image: url(<%=cl_image_path(@dream.photos[3].key)%>)"></div>
  <div class="image-div div5" style="background-image: url(<%=cl_image_path(@dream.photos[4].key)%>)"></div>
  <%= render partial: "shared/modal_dream_show", locals: {dream: @dream} %>
</div>

  <div class="row">
    <div class="col-6 mt-3">
      <h3><%= @dream.user.email[/^(.+)@/, 1].capitalize %> is happy to propose you this dream !</h3>

      <p>
        <%= @dream.description %>
      </p>
      <p>
        <% if @dream.bookings.count > 0 %>
          <em>This dream has already been booked <strong><%= @dream.bookings.count %></strong> !</em>
        <% end %>
      </p>
    <% if user_signed_in? && current_user == @dream.user %>
      <%= link_to "Delete", dream_path(@dream), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, id: "delete-button", class: "btn btn-primary text-decoration-none"%>
      <%= link_to "Edit", edit_dream_path(@dream), data: { turbo_action: "replace", turbo_frame: "dream-form" }, id: "delete-button", class: "btn btn-primary text-decoration-none" %>
    <% end %>
    </div>
    <% unless user_signed_in? && current_user == @dream.user %>
      <div id="price-info" class="col-6 mt-3 mx-auto text-center">
        <% if @dream.availability %>
          <div class="mt-5">
            The price of this dream is <%= number_with_delimiter(@dream.price.round(), delimiter: ' ') %>€ per day of booking ! <br><br>
            This dream is currently available ! <br><br>
          </div>
          <%= link_to "Book it!", new_dream_booking_path(@dream), id: "booking-button", class: "btn text-decoration-none" %>
        <% else %>
          Unfortunately, we are unable to offer bookings for this dream 😞...
        <% end %>
      </div>
    <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DreamsRUs</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%#= render "shared/navbar" %>
    <%#= render "shared/flashes" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
    <h2>Bookings made at your dreams !</h2>
    <%= render partial: "shared/dashboard_booking_received_table", locals: {dreams: @dreams} %>
  </div>

<div class="container">
  <div class="parent-dash">
    <div >
      <h2>Dreams you created !</h2>
      <%= render partial: "shared/dashboard_dream_table", locals: {dreams: @dreams} %>
    </div>
    <div >
      <h2>Bookings you made !</h2>
      <%= render partial: "shared/dashboard_booking_sent_table", locals: {bookings: @bookings} %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h3>coucou</h3>
<h1>hello world</h1>

<%= link_to "log_out", destroy_user_session_path, method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>

app/views/shared/_caroussel.html.erb
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="<%=cl_image_path(@dream.photos[0].key)%>" class="d-block w-100" alt="First image">
    </div>
    <div class="carousel-item">
      <img src="<%=cl_image_path(@dream.photos[1].key)%>" class="d-block w-100" alt="Second image">
    </div>
    <div class="carousel-item">
      <img src="<%=cl_image_path(@dream.photos[2].key)%>" class="d-block w-100" alt="Third image">
    </div>
    <div class="carousel-item">
      <img src="<%=cl_image_path(@dream.photos[3].key)%>" class="d-block w-100" alt="Fourth image">
    </div>
    <div class="carousel-item">
      <img src="<%=cl_image_path(@dream.photos[4].key)%>" class="d-block w-100" alt="Fifth image">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_dashboard_booking_received_table.html.erb
<table class="table table-light">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Dream name</th>
        <th scope="col">Mail of the requester</th>
        <th scope="col">Total price</th>
        <th scope="col">Start date</th>
        <th scope="col">End date</th>
        <th scope="col">Status of the booking</th>
      </tr>
    </thead>
    <tbody>
    <% @dreams.each do |dream| %>
      <% dream.bookings.each_with_index do |booking, index| %>
        <% if index.even?  %>
          <tr class="table-warning">
            <th scope="row"><%= index + 1 %></th>
            <td><%= booking.dream.title %></td>
            <td><%= booking.user.email %></td>
            <td><%= number_with_delimiter(((booking.end_date&.to_datetime&.-(booking.start_date&.to_datetime)).to_i * booking.dream.price).round(), delimiter: ' ') %>€</td>
            <td><%= booking.start_date&.strftime('%B %e, %Y') %></td>
            <td><%= booking.end_date&.strftime('%B %e, %Y') %></td>
            <td>
              <% if booking.pending? %>
                <%= link_to "Accept the booking", accept_booking_dream_booking_path(booking.dream, booking), class: "btn btn-success" %>
                <%= link_to "Refuse the booking", refuse_booking_dream_booking_path(booking.dream, booking), class: "btn btn-danger" %>
              <% elsif booking.accepted? %>
                Accepted
              <% else  %>
                Refused
              <% end  %>
            </td>
          </tr>
        <% else %>
          <tr class="table-danger">
            <th scope="row"><%= index + 1 %></th>
            <td><%= booking.dream.title %></td>
            <td><%= booking.user.email %></td>
            <td><%= number_with_delimiter(((booking.end_date&.to_datetime&.-(booking.start_date&.to_datetime)).to_i * booking.dream.price).round(), delimiter: ' ') %>€</td>
            <td><%= booking.start_date&.strftime('%B %e, %Y') %></td>
            <td><%= booking.end_date&.strftime('%B %e, %Y') %></td>
            <td>
              <% if booking.pending? %>
                <%= link_to "Accept the booking", accept_booking_dream_booking_path(booking.dream, booking), class: "btn btn-success" %>
                <%= link_to "Refuse the booking", refuse_booking_dream_booking_path(booking.dream, booking), class: "btn btn-danger" %>
              <% elsif booking.accepted? %>
                Accepted
              <% else  %>
                Refused
              <% end  %>
            </td>
          </tr>
        <% end %>
      <% end %>
    <% end %>

      </tbody>
    </table>

app/views/shared/_dashboard_booking_sent_table.html.erb
<table class="table table-light">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Dream name</th>
        <th scope="col">Price</th>
        <th scope="col">Category</th>
        <th scope="col">Start date</th>
        <th scope="col">End date</th>
        <th scope="col">Booking status</th>
      </tr>
    </thead>
    <tbody>
    <% @bookings.each_with_index do |booking, index| %>
        <% if index.even?  %>
          <tr class="table-warning">
            <th scope="row"><%= index + 1 %></th>
            <td><%= link_to booking.dream.title, dream_booking_path(booking.dream, booking), class: "hover-link-1" %></td>
            <td><%= number_with_delimiter(((booking.end_date&.to_datetime&.-(booking.start_date&.to_datetime)).to_i * booking.dream.price).round(), delimiter: ' ') %>€</td>
            <td><%= booking.dream.category %></td>
            <td><%= booking.start_date&.strftime('%B %e, %Y') %></td>
            <td><%= booking.end_date&.strftime('%B %e, %Y') %></td>
            <td><%= booking&.status %></td>
          </tr>
        <% else %>
          <tr class="table-danger">
            <th scope="row"><%= index + 1 %></th>
            <td><%= link_to booking.dream.title, dream_booking_path(booking.dream, booking), class: "hover-link-1" %></td>
            <td><%= number_with_delimiter(((booking.end_date&.to_datetime&.-(booking.start_date&.to_datetime)).to_i * booking.dream.price).round(), delimiter: ' ') %>€</td>
            <td><%= booking.dream.category %></td>
            <td><%= booking.start_date.strftime('%B %e, %Y') %></td>
            <td><%= booking.end_date.strftime('%B %e, %Y') %></td>
            <td><%= booking&.status %></td>
          </tr>
        <% end %>
      <% end %>

      </tbody>
    </table>

app/views/shared/_dashboard_booking_table.html.erb
<table class="table table-light">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Dream name</th>
        <th scope="col">Price</th>
        <th scope="col">Category</th>
        <th scope="col">Description</th>
        <th scope="col">Start date</th>
        <th scope="col">End date</th>
      </tr>
    </thead>
    <tbody>
    <% @bookings.each_with_index do |booking, index| %>
        <% if index % 2 === 0  %>
          <tr class="table-warning">
            <th scope="row"><%= index + 1 %></th>
            <td><%= link_to booking.dream.title, dream_path(booking.dream), class: "hover-link-1" %></td>
            <td><%= number_with_delimiter(booking.dream.price.to_i, delimiter: ' ') %>€</td>
            <td><%= booking.dream.category %></td>
            <td><%= booking.dream.description %></td>
            <td><%= booking.start_date.strftime('%B %e, %Y') %></td>
            <td><%= booking.end_date.strftime('%B %e, %Y') %></td>
          </tr>
        <% else %>
          <tr class="table-danger">
            <th scope="row"><%= index + 1 %></th>
            <td><%= link_to booking.dream.title, dream_path(booking.dream), class: "hover-link-1" %></td>
            <td><%= number_with_delimiter(booking.dream.price.to_i, delimiter: ' ') %>€</td>
            <td><%= booking.dream.category %></td>
            <td><%= booking.dream.description %></td>
            <td><%= booking.start_date.strftime('%B %e, %Y') %></td>
            <td><%= booking.end_date.strftime('%B %e, %Y') %></td>
          </tr>
        <% end %>
      <% end %>

      </tbody>
    </table>

app/views/shared/_dashboard_dream_table.html.erb
<table class="table table-light">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Dream name</th>
        <th scope="col">Price</th>
        <th scope="col">Category</th>
        <th scope="col">Description</th>
      </tr>
    </thead>
    <tbody>
    <% @dreams.each_with_index do |dream, index| %>
        <% if index.even?  %>
          <tr class="table-warning">
            <th scope="row"><%= index + 1 %></th>
            <td><%= link_to dream.title, dream_path(dream), class: "hover-link-1" %></td>
            <td><%= number_with_delimiter(dream.price.to_i, delimiter: ' ') %>€</td>
            <td><%= dream.category %></td>
            <td><%= dream.description %></td>
          </tr>
        <% else %>
          <tr class="table-danger">
            <th scope="row"><%= index + 1 %></th>
            <td><%= link_to dream.title, dream_path(dream), class: "hover-link-1" %></td>
            <td><%= number_with_delimiter(dream.price.to_i, delimiter: ' ') %>€</td>
            <td><%= dream.category %></td>
            <td><%= dream.description %></td>
          </tr>
        <% end %>
      <% end %>

      </tbody>
    </table>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-light custom-navbar">
  <div class="container-fluid">
    <%= link_to root_path, class: "right-element navbar-brand" do %>
      <%= image_tag("https://res.cloudinary.com/dcvyn1qtm/image/upload/v1700651209/development/logo-png_iqwkcu.png", crop: :fill) %>
      <div class="name">
        <p>Dreams R Us</p>
      </div>
    <% end %>



  <div class="search-bar-container text-white">
    <%= form_tag(search_dreams_path, method: :get, class: "search-form") do %>
      <div class="search-input-container text-white">
        <%= text_field_tag :q, params[:q], class: 'form-control me-2 search-bar text-white', placeholder: 'Search', aria_label: 'Search' %>
      <div class="search-icon-container text-white" onclick="submitSearch()">
        <i class="fa-solid fa-magnifying-glass"></i>
      </div>
      </div>
    <% end %>
  </div>

<script>
  function submitSearch() {
    document.querySelector('.search-form').submit();
  }
</script>


    <div class="left-element">
      <div class="new_entry">
        <%= link_to "new dream", new_dream_path, class: "m-4 btn btn-light text-decoration-none dream_text_effect text-white ms-5" %>
      </div>
     <div class="nav-item dropdown">
      <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
        aria-expanded="false">
        <div class="lines">
          <%= image_tag("https://res.cloudinary.com/dcvyn1qtm/image/upload/v1700651990/line_22_u7gw1o.svg", crop: :fill, class: "line") %>
          <%= image_tag("https://res.cloudinary.com/dcvyn1qtm/image/upload/v1700651990/line_22_u7gw1o.svg", crop: :fill, class: "line") %>
          <%= image_tag("https://res.cloudinary.com/dcvyn1qtm/image/upload/v1700651990/line_22_u7gw1o.svg", crop: :fill, class: "line") %>
        </div>
         <div class="frame">
        <div class="overlap-group"><%= image_tag("https://res.cloudinary.com/dcvyn1qtm/image/upload/v1700651989/Frame_18_ftplpx.svg", crop: :fill) %>
        </div>
      </div>
      </a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <% if user_signed_in?  %>
          <li><%= link_to "My dashboard", dashboard_path, class: "dropdown-item" %></li>
          <li><%= link_to "My profile", edit_user_registration_path, class: "dropdown-item" %></li>
          <li><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
        <% else  %>
          <li><%= link_to "Log in", new_user_session_path,  class: "dropdown-item" %></li>
        <% end  %>
      </ul>
      </div>
    </div>

  </div>
</nav>



<script>
  function submitSearch() {
    document.querySelector('.search-form').submit();
  }
</script>